[context.production]
 command="npm run build"
 publish="build"
[context.production.enviroment]
 REACT_APP_HEADING="Production"

[context.staging]
 command="npm run build"
 publish="build"
[context.staging.enviroment]
    REACT_APP_HEADING="Staging"